apiVersion: v1
kind: Service
metadata:
  name: {{ include "golang-api.fullname" . }}
  labels:
    {{- include "golang-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    {{- include "golang-api.selectorLabels" . | nindent 4 }}

