FROM docker.io/library/alpine:3.16.0 AS builder

ENV JENKINS_VERSION war-stable/2.346.2
ENV JENKINS_URL https://get.jenkins.io/${JENKINS_VERSION}/jenkins.war

ENV JENKINS_USER jenkins
ENV JENKINS_HOME /home/${JENKINS_USER}


RUN apk update
RUN apk upgrade --available
RUN apk add --no-cache wget

RUN addgroup -S ${JENKINS_USER} && adduser -S ${JENKINS_USER} -G ${JENKINS_USER}
USER ${JENKINS_USER}

WORKDIR ${JENKINS_HOME}

RUN wget ${JENKINS_URL} -P ${JENKINS_HOME}

USER root

RUN apk del wget

# # #

FROM builder AS final
USER root

RUN apk add --no-cache openjdk8-jre

USER ${JENKINS_USER}

WORKDIR ${JENKINS_HOME} 

COPY --from=builder ${JENKINS_HOME}/jenkins.war ${JENKINS_HOME}/jenkins.war


CMD ["/usr/bin/java","-jar","jenkins.war"]
