FROM docker.io/library/debian:bookworm-slim

RUN apt-get update
RUN apt-get dist-upgrade -y
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y ruby ruby-dev ubuntu-dev-tools

RUN useradd -u 8877 -s /bin/bash non-root

RUN gem install jekyll bundler

#USER non-root

WORKDIR /home/non-root

RUN jekyll new my-awesome-site
WORKDIR /home/non-root/my-awesome-site

CMD ["bundle","exec","jekyll","serve","--host","0.0.0.0"]
